name: Build and run all tests with Dagger
on: [workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - uses: actions/checkout@v3
      - name: Build and run all tests with Dagger
        env:
          GOLANG_IMAGE: "golang:latest"
        run: cd ./dagger-pipeline && go run main.go
